#!/usr/bin/env python3
"""Inline-agent Integration Service (IS) connector tool check.

Design-time checks only — this script does NOT invoke the connector.

Combines the F8 (standalone IS tool) resource-shape assertions with
the F2 (inline agent) flow-wiring assertions. Specifically:

  1. The flow file contains a `uipath.agent.autonomous` node whose
     `inputs.source` points at the inline agent's UUID subdirectory.
  2. The flow file contains a `uipath.agent.resource.tool.connector`
     node.
  3. An edge wires the agent's `tool` handle (source) to the connector
     node's `input` handle (target), per the flow-integration spec.
  4. Inside the inline agent's subdirectory, a resource.json under
     `resources/` declares an IS tool, GENERATED by
     `uip agent refresh --inline-in-flow` (not hand-authored) from the
     connector node's configured values joined with live IS metadata:
       - $resourceType == "tool", type == "integration",
         location == "external"
       - properties.connection.id is a non-empty string (connection wired)
       - properties.parameters is a non-empty array
       - Web Search shape: the `provider` param is `fieldVariant: "static"`
         with a concrete (non-{{prompt}}) value — a single-value enum is
         baked static — and carries NO `enum` in inputSchema (a static
         field with an enum breaks the agent runtime's model build); the
         free-text `query` param is `fieldVariant: "dynamic"`.
  5. At least one `bindings_v2.json` exists under the flow project
     (outside `.agent-builder/`) — generated by `uip agent refresh
     --inline-in-flow --bindings-target`.
  6. The same refresh provisions the solution connection resource: at
     least one connection resource file exists under
     `ResearchFlowSol/resources/solution_folder/connection/`. (The
     inline-in-flow refresh path provisions it; no separate
     `uip solution resources refresh` step is required.)
"""

import json
import os
import sys
from pathlib import Path

sys.path.insert(0, os.path.dirname(os.path.dirname(os.path.dirname(os.path.abspath(__file__)))))
from _shared.inline_wiring import find_inline_resource  # noqa: E402

INLINE_AGENT_NODE_TYPE = "uipath.agent.autonomous"
# Connector tool nodes carry the connector-key + activity in the type suffix
# (e.g. `uipath.agent.resource.tool.connector.uipath-slack.send-message`),
# so match on the prefix. Trailing "." disambiguates from any future bare type.
CONNECTOR_TOOL_NODE_TYPE_PREFIX = "uipath.agent.resource.tool.connector."

SOLUTION = Path(os.getcwd()) / "ResearchFlowSol"
FLOW_PROJECT = SOLUTION / "ResearchFlow"
FLOW_PATH = FLOW_PROJECT / "ResearchFlow.flow"
CONNECTION_DIR = SOLUTION / "resources" / "solution_folder" / "connection"


def load(path: Path) -> dict:
    if not path.is_file():
        sys.exit(f"FAIL: Missing {path}")
    try:
        return json.loads(path.read_text())
    except json.JSONDecodeError as e:
        sys.exit(f"FAIL: {path} is not valid JSON: {e}")


def assert_agent_and_connector_nodes(flow: dict) -> tuple:
    nodes = flow.get("nodes") or []
    agent_nodes = [n for n in nodes if n.get("type") == INLINE_AGENT_NODE_TYPE]
    if not agent_nodes:
        sys.exit(
            f"FAIL: flow has no node of type {INLINE_AGENT_NODE_TYPE!r}"
        )
    agent_node = agent_nodes[0]

    connector_nodes = [
        n for n in nodes
        if isinstance(n.get("type"), str)
        and n["type"].startswith(CONNECTOR_TOOL_NODE_TYPE_PREFIX)
    ]
    if not connector_nodes:
        sys.exit(
            f"FAIL: flow has no node with type starting with "
            f"{CONNECTOR_TOOL_NODE_TYPE_PREFIX!r} — the IS connector tool was "
            "not added to the flow canvas"
        )
    connector_node = connector_nodes[0]

    if not agent_node.get("id"):
        sys.exit(f"FAIL: {INLINE_AGENT_NODE_TYPE} node has no id")
    if not connector_node.get("id"):
        sys.exit(f"FAIL: connector tool node has no id")

    print(
        f"OK: flow has {INLINE_AGENT_NODE_TYPE!r} and connector tool node "
        f"{connector_node['type']!r}"
    )
    return agent_node, connector_node


def assert_agent_source_dir(agent_node: dict) -> Path:
    inputs = agent_node.get("inputs") or {}
    source = inputs.get("source")
    if not isinstance(source, str) or not source:
        sys.exit(
            f"FAIL: {INLINE_AGENT_NODE_TYPE} node has no inputs.source"
        )
    agent_dir = FLOW_PATH.parent / source
    if not agent_dir.is_dir():
        sys.exit(
            f"FAIL: inputs.source {source!r} does not point to an existing "
            f"directory ({agent_dir})"
        )
    print(f"OK: inline agent directory resolves to {agent_dir.name}")
    return agent_dir


def assert_tool_edge(flow: dict, agent_id: str, connector_id: str) -> None:
    edges = flow.get("edges") or []
    matching = [
        e for e in edges
        if e.get("sourceNodeId") == agent_id
        and e.get("sourcePort") == "tool"
        and e.get("targetNodeId") == connector_id
        and e.get("targetPort") == "input"
    ]
    if not matching:
        sys.exit(
            "FAIL: no edge wires the agent's 'tool' handle (source) to the "
            "connector node's 'input' handle (target). Expected an edge with "
            f"sourceNodeId={agent_id!r}, sourcePort='tool', "
            f"targetNodeId={connector_id!r}, targetPort='input'."
        )
    print("OK: agent 'tool' handle is wired to connector node's 'input' handle")


def _param(data: dict, name: str):
    params = (data.get("properties") or {}).get("parameters") or []
    for p in params:
        if isinstance(p, dict) and p.get("name") == name:
            return p
    return None


def assert_integration_tool_resource(agent_dir: Path) -> None:
    path, data = find_inline_resource(
        agent_dir,
        lambda d: d.get("$resourceType") == "tool" and d.get("type") == "integration",
        description='IS tool ($resourceType=="tool", type=="integration")',
    )
    rid = data.get("id")
    if not isinstance(rid, str) or "-" not in rid:
        sys.exit(f"FAIL: IS tool id missing or malformed at {path}: {rid!r}")
    if not data.get("isEnabled"):
        sys.exit(f"FAIL: IS tool isEnabled must be truthy at {path}")
    if data.get("location") != "external":
        sys.exit(
            f"FAIL: IS tool location should be 'external', got "
            f"{data.get('location')!r} at {path}"
        )

    props = data.get("properties") or {}
    conn_id = (props.get("connection") or {}).get("id")
    if not isinstance(conn_id, str) or not conn_id:
        sys.exit(
            f"FAIL: properties.connection.id missing/empty at {path} — "
            "the connection was not wired into the generated resource.json"
        )
    params = props.get("parameters")
    if not isinstance(params, list) or not params:
        sys.exit(f"FAIL: properties.parameters missing or empty at {path}")

    # Web Search shape — the feature's key, hard-won behaviors:
    #  - provider is a single-value enum → baked STATIC (the agent must not be
    #    asked to echo it) and carries NO enum in inputSchema (a static field
    #    with an enum breaks the agent runtime's model build).
    #  - query is free-text → DYNAMIC (agent-decided).
    provider = _param(data, "provider")
    query = _param(data, "query")
    if provider is None:
        sys.exit(f"FAIL: no 'provider' parameter on the Web Search tool at {path}")
    if provider.get("fieldVariant") != "static":
        sys.exit(
            "FAIL: 'provider' should be fieldVariant 'static' (single-value "
            f"enum baked static), got {provider.get('fieldVariant')!r} at {path}"
        )
    pval = provider.get("value")
    if not isinstance(pval, str) or pval.startswith("{{prompt"):
        sys.exit(
            f"FAIL: 'provider' should carry a concrete static value, got "
            f"{pval!r} at {path}"
        )
    if query is None:
        sys.exit(f"FAIL: no 'query' parameter on the Web Search tool at {path}")
    if query.get("fieldVariant") != "dynamic":
        sys.exit(
            "FAIL: 'query' should be fieldVariant 'dynamic' (agent-decided), "
            f"got {query.get('fieldVariant')!r} at {path}"
        )
    schema_provider = (
        (data.get("inputSchema") or {}).get("properties") or {}
    ).get("provider") or {}
    if "enum" in schema_provider:
        sys.exit(
            "FAIL: 'provider' must NOT carry an enum in inputSchema (it's a "
            f"static field — an enum there breaks the model build) at {path}"
        )

    print(
        f'OK: {path.relative_to(SOLUTION.parent)} is a generated IS tool '
        f"(type=integration, location=external, connection wired, "
        f"provider static / query dynamic) (id={rid})"
    )


def assert_bindings_v2_authored() -> None:
    candidates = sorted(FLOW_PROJECT.rglob("bindings_v2.json"))
    authored = [p for p in candidates if ".agent-builder" not in p.parts]
    if not authored:
        sys.exit(
            f"FAIL: no bindings_v2.json under {FLOW_PROJECT} (outside "
            ".agent-builder/). `uip agent refresh --inline-in-flow "
            "--bindings-target` generates it as the source for "
            "`uip solution resources refresh`."
        )
    path = authored[0]
    try:
        data = json.loads(path.read_text())
    except json.JSONDecodeError as e:
        sys.exit(f"FAIL: {path} is not valid JSON: {e}")
    if not isinstance(data, (dict, list)):
        sys.exit(f"FAIL: {path} root is neither object nor array: {type(data).__name__}")
    print(f"OK: bindings_v2.json authored at {path.relative_to(SOLUTION.parent)}")


def assert_connection_provisioned() -> None:
    if not CONNECTION_DIR.is_dir():
        sys.exit(
            f"FAIL: {CONNECTION_DIR} does not exist — `uip agent refresh "
            "--inline-in-flow` did not provision a connection resource under "
            "resources/solution_folder/connection/"
        )
    connection_files = [p for p in CONNECTION_DIR.rglob("*.json") if p.is_file()]
    if not connection_files:
        sys.exit(
            f"FAIL: {CONNECTION_DIR} is empty — refresh did not drop any "
            "connection resource JSON files"
        )
    print(
        f"OK: found {len(connection_files)} connection resource file(s) under "
        f"resources/solution_folder/connection/"
    )


def main() -> None:
    if not SOLUTION.is_dir():
        sys.exit(f"FAIL: Solution directory {SOLUTION} does not exist")
    flow = load(FLOW_PATH)

    agent_node, connector_node = assert_agent_and_connector_nodes(flow)
    agent_dir = assert_agent_source_dir(agent_node)
    assert_tool_edge(flow, agent_node["id"], connector_node["id"])
    assert_integration_tool_resource(agent_dir)
    assert_bindings_v2_authored()
    assert_connection_provisioned()


if __name__ == "__main__":
    main()
