#!/usr/bin/env python3
"""Validate the Aged Invoice Payment solution-level SDD output.

The task intentionally allows the planner to choose exact kebab-case filenames.
This checker therefore discovers generated SDD markdown files by content, then
asserts the behaviors that matter:

- a solution overview SDD with Planner Handoff and solution scope
- per-product SDD coverage for Case, Maestro Flow, Coded Apps, API Workflows,
  Agents, and RPA
- AP aged-invoice domain markers from the PDD survive into the design
- no unresolved template placeholders or implementation artifacts appear
"""

from __future__ import annotations

import re
import sys
from pathlib import Path


ROOT = Path.cwd()

PRODUCT_SIGNATURES: dict[str, list[str]] = {
    "Case Management": [
        r"case lifecycle diagram",
        r"\bstages\b",
        r"tasks grid",
        r"case management",
    ],
    "Maestro Flow": [
        r"flow overview",
        r"nodes inventory",
        r"maestro",
        r"integrated components",
    ],
    "Coded Apps": [
        r"app type\s*&\s*tech stack",
        r"pages\s*&\s*routes",
        r"coded apps?",
        r"ap control tower",
    ],
    "API Workflows": [
        r"input schema",
        r"output schema",
        r"execution flow",
        r"api workflows?",
    ],
    "Agents": [
        r"agent overview",
        r"agent framework",
        r"\btools\b",
        r"payment risk agent|invoice triage agent",
    ],
    "RPA": [
        r"process map",
        r"workflow inventory",
        r"\brpa\b",
        r"mock erp|supplier statement",
    ],
}

DOMAIN_MARKERS = [
    "Aged Invoice Payment",
    "Missing GRN",
    "Price mismatch",
    "Duplicate",
    "Payment hold",
    "Urgent payment",
    "AP Control Tower",
    "Case Workspace",
    "Data Fabric",
    "SLA",
    "Payment Risk Agent",
    "Supplier 360",
]

IMPLEMENTATION_PATTERNS = [
    "caseplan.json",
    "*.flow",
    "*.xaml",
    "agent.json",
    "project.json",
    "*.uipx",
    "*tasks.md",
]


def fail(message: str) -> None:
    sys.exit(f"FAIL: {message}")


def read(path: Path) -> str:
    return path.read_text(encoding="utf-8", errors="replace")


def norm(text: str) -> str:
    return text.lower()


def generated_sdds() -> list[Path]:
    files: list[Path] = []
    for path in sorted(ROOT.glob("*.md")):
        if path.name == "pdd.md":
            continue
        text = read(path)
        if "solution design document" in text.lower() or "planner handoff" in text.lower():
            files.append(path)
    if not files:
        fail("no generated SDD markdown files found in sandbox root")
    return files


def find_solution_overview(files: list[Path]) -> tuple[Path, str]:
    candidates: list[tuple[int, Path, str]] = []
    for path in files:
        text = read(path)
        lower = text.lower()
        score = 0
        if "planner handoff" in lower:
            score += 2
        if "sdd scope" in lower and "solution" in lower:
            score += 3
        if "project inventory" in lower:
            score += 2
        if "cross-project data flow" in lower:
            score += 2
        if "per-project sdd index" in lower:
            score += 1
        if "solution-sdd" in path.name.lower():
            score += 1
        if score:
            candidates.append((score, path, text))

    if not candidates:
        fail("no solution overview SDD candidate found")

    candidates.sort(reverse=True, key=lambda item: item[0])
    return candidates[0][1], candidates[0][2]


def count_product_signatures(text: str, patterns: list[str]) -> int:
    lower = norm(text)
    return sum(1 for pattern in patterns if re.search(pattern, lower, re.IGNORECASE))


def check_solution_overview(path: Path, text: str) -> None:
    required = [
        "Planner Handoff",
        "planner-handoff:v1",
        "Execution autonomy",
        "Delivery model",
        "SDD scope",
        "Generated by",
        "uipath-planner",
        "Recommended Scope",
        "Project Inventory",
        "Cross-Project Data Flow",
        "Per-Project SDD Index",
    ]
    missing = [marker for marker in required if marker.lower() not in text.lower()]
    if missing:
        fail(f"{path.name} missing solution overview markers: {missing}")

    if not re.search(r"recommendation\s*:\s*.*solution", text, re.IGNORECASE):
        fail(f"{path.name} does not record a Solution recommendation")

    if not re.search(r"\|[^\n]*sdd scope[^\n]*\|[^\n]*solution", text, re.IGNORECASE):
        fail(f"{path.name} Planner Handoff does not set SDD scope to solution")


def check_product_decomposition(files: list[Path]) -> None:
    coverage: dict[str, list[str]] = {product: [] for product in PRODUCT_SIGNATURES}

    for path in files:
        text = read(path)
        for product, patterns in PRODUCT_SIGNATURES.items():
            if count_product_signatures(text, patterns) >= 3:
                coverage[product].append(path.name)

    missing = [product for product, matches in coverage.items() if not matches]
    if missing:
        details = ", ".join(
            f"{product}={matches or '-'}" for product, matches in coverage.items()
        )
        fail(f"missing per-product SDD coverage for {missing}; coverage: {details}")

    if len(files) < 4:
        fail(
            f"expected a solution overview plus multiple per-project SDDs; "
            f"found only {len(files)} generated SDD file(s): {[p.name for p in files]}"
        )


def check_domain_fidelity(all_text: str) -> None:
    lower = all_text.lower()
    missing = [marker for marker in DOMAIN_MARKERS if marker.lower() not in lower]
    if len(missing) > 2:
        fail(f"too many PDD domain markers missing from SDD set: {missing}")

    scenario_patterns = [
        r"missing\s+grn|missing\s+goods\s+receipt",
        r"price\s+mismatch|price\s+variance",
        r"duplicate\s+(invoice\s+)?risk",
        r"payment\s+hold",
        r"supplier\s+statement",
        r"urgent\s+payment",
    ]
    missing_scenarios = [
        pattern
        for pattern in scenario_patterns
        if not re.search(pattern, lower, re.IGNORECASE)
    ]
    if missing_scenarios:
        fail(f"missing exception/demo scenario coverage: {missing_scenarios}")


def check_no_placeholders(all_text: str) -> None:
    placeholders = sorted(set(re.findall(r"<[A-Z][A-Z0-9_]{2,}>", all_text)))
    if placeholders:
        fail(f"unresolved template placeholders found: {placeholders[:10]}")


def check_no_implementation_artifacts() -> None:
    found: list[str] = []
    for pattern in IMPLEMENTATION_PATTERNS:
        for path in ROOT.rglob(pattern):
            if ".venv" in path.parts:
                continue
            found.append(str(path.relative_to(ROOT)))
    if found:
        fail(f"implementation artifacts were created during SDD-only task: {found[:10]}")


def main() -> None:
    files = generated_sdds()
    overview_path, overview_text = find_solution_overview(files)
    all_text = "\n\n".join(read(path) for path in files)

    check_solution_overview(overview_path, overview_text)
    check_product_decomposition(files)
    check_domain_fidelity(all_text)
    check_no_placeholders(all_text)
    check_no_implementation_artifacts()

    print(
        "OK: solution overview and per-product SDD coverage validated; "
        f"files={', '.join(path.name for path in files)}"
    )


if __name__ == "__main__":
    main()
